In [2]:
import numpy as np
import pandas as pd
from glob import glob

Read Single CSV file

In [3]:
single_file_acc = pd.read_csv("../../data/raw/MetaMotion/MetaMotion/A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv")

In [4]:
single_file_gyro = pd.read_csv("../../data/raw/MetaMotion/MetaMotion/A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Gyroscope_25.000Hz_1.4.4.csv")

List All the Data Files

In [5]:
files = glob("../../data/raw/MetaMotion/MetaMotion/*.csv")

In [6]:
len(files)

187

Extract features from

In [7]:
files[0]

'../../data/raw/MetaMotion/MetaMotion\\A-bench-heavy2-rpe8_MetaWear_2019-01-11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv'

In [8]:
data_path = "../../data/raw/MetaMotion/MetaMotion/*.csv"

In [9]:
f = files[0]

In [10]:
f.split("-")

['../../data/raw/MetaMotion/MetaMotion\\A',
 'bench',
 'heavy2',
 'rpe8_MetaWear_2019',
 '01',
 '11T16.10.08.270_C42732BE255C_Accelerometer_12.500Hz_1.4.4.csv']

In [11]:
participant = f.split("-")[0].split("\\")[-1]

In [12]:
label = f.split("-")[1]

In [13]:
category = f.split("-")[2].rstrip("_MetaWear_2019")

In [14]:
df = pd.read_csv(f)

In [15]:
df["participant"] = participant
df["label"] = label
df["category"] = category

In [16]:
df.head()

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,label,category
0,1547219408431,2019-01-11T16:10:08.431,0.00,0.010,0.964,-0.087,A,bench,heavy
1,1547219408511,2019-01-11T16:10:08.511,0.08,0.000,0.961,-0.069,A,bench,heavy
2,1547219408591,2019-01-11T16:10:08.591,0.16,0.001,0.974,-0.087,A,bench,heavy
3,1547219408671,2019-01-11T16:10:08.671,0.24,-0.012,0.971,-0.084,A,bench,heavy
4,1547219408751,2019-01-11T16:10:08.751,0.32,-0.013,0.954,-0.094,A,bench,heavy

Read All the files

In [17]:
acc_df = pd.DataFrame()
gyro_df = pd.DataFrame()

In [18]:
acc_set = 1
gyro_set = 1

In [19]:
for f in files:
    participant= f.split("-")[0].split("\\")[-1]
    label = f.split("-")[1]
    category = f.split("-")[2].rstrip("_MetaWear_2019")
    
    df = pd.read_csv(f)
    
    df["participant"] = participant
    df["label"] = label
    df["category"] = category
    
    if "Accelerometer" in f:
        df["set"] = acc_set
        acc_set += 1
        acc_df = pd.concat([acc_df, df], ignore_index=True)
        
    elif "Gyroscope" in f:
        df["set"] = gyro_set
        gyro_set += 1
        gyro_df = pd.concat([gyro_df, df], ignore_index=True)

In [20]:
acc_df.head()

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
0,1547219408431,2019-01-11T16:10:08.431,0.00,0.010,0.964,-0.087,A,bench,heavy,1
1,1547219408511,2019-01-11T16:10:08.511,0.08,0.000,0.961,-0.069,A,bench,heavy,1
2,1547219408591,2019-01-11T16:10:08.591,0.16,0.001,0.974,-0.087,A,bench,heavy,1
3,1547219408671,2019-01-11T16:10:08.671,0.24,-0.012,0.971,-0.084,A,bench,heavy,1
4,1547219408751,2019-01-11T16:10:08.751,0.32,-0.013,0.954,-0.094,A,bench,heavy,1

In [21]:
acc_df[acc_df["set"] == 10]

,epoch (ms),time (01:00),elapsed (s),x-axis (g),y-axis (g),z-axis (g),participant,label,category,set
2210,1547221285010,2019-01-11T16:41:25.010,0.00,-0.107,0.948,-0.004,A,ohp,heavy,10
2211,1547221285090,2019-01-11T16:41:25.090,0.08,-0.137,1.417,-0.084,A,ohp,heavy,10
2212,1547221285170,2019-01-11T16:41:25.170,0.16,-0.220,1.425,-0.054,A,ohp,heavy,10
2213,1547221285250,2019-01-11T16:41:25.250,0.24,-0.221,1.138,-0.027,A,ohp,heavy,10
2214,1547221285330,2019-01-11T16:41:25.330,0.32,-0.254,0.940,-0.024,A,ohp,heavy,10
...,...,...,...,...,...,...,...,...,...,...
2363,1547221297250,2019-01-11T16:41:37.250,12.24,-0.185,0.926,-0.044,A,ohp,heavy,10
2364,1547221297330,2019-01-11T16:41:37.330,12.32,-0.136,0.678,-0.048,A,ohp,heavy,10
2365,1547221297410,2019-01-11T16:41:37.410,12.40,-0.097,0.739,-0.070,A,ohp,heavy,10
2366,1547221297490,2019-01-11T16:41:37.490,12.48,-0.155,1.021,-0.043,A,ohp,heavy,10
2367,1547221297570,2019-01-11T16:41:37.570,12.56,-0.160,0.866,-0.014,A,ohp,heavy,10

Working with Datetimes

In [22]:
acc_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23578 entries, 0 to 23577
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   epoch (ms)    23578 non-null  int64
 1   time (01:00)  23578 non-null  object
 2   elapsed (s)   23578 non-null  float64
 3   x-axis (g)    23578 non-null  float64
 4   y-axis (g)    23578 non-null  float64
 5   z-axis (g)    23578 non-null  float64
 6   participant   23578 non-null  object
 7   label         23578 non-null  object
 8   category      23578 non-null  object
 9   set           23578 non-null  int64
dtypes: float64(4), int64(2), object(4)
memory usage: 1.8+ MB

In [23]:
pd.to_datetime(df["epoch (ms)"], unit="ms")

0     2019-01-16 19:14:03.834
1     2019-01-16 19:14:03.874
2     2019-01-16 19:14:03.914
3     2019-01-16 19:14:03.954
4     2019-01-16 19:14:03.994
                ...
487   2019-01-16 19:14:23.314
488   2019-01-16 19:14:23.354
489   2019-01-16 19:14:23.394
490   2019-01-16 19:14:23.434
491   2019-01-16 19:14:23.474
Name: epoch (ms), Length: 492, dtype: datetime64[ns]

In [24]:
pd.to_datetime(df["time (01:00)"])

0     2019-01-16 20:14:03.834
1     2019-01-16 20:14:03.874
2     2019-01-16 20:14:03.914
3     2019-01-16 20:14:03.954
4     2019-01-16 20:14:03.994
                ...
487   2019-01-16 20:14:23.314
488   2019-01-16 20:14:23.354
489   2019-01-16 20:14:23.394
490   2019-01-16 20:14:23.434
491   2019-01-16 20:14:23.474
Name: time (01:00), Length: 492, dtype: datetime64[ns]

In [25]:
acc_df.index = pd.to_datetime(acc_df["epoch (ms)"], unit="ms")

In [26]:

gyro_df.index = pd.to_datetime(gyro_df["epoch (ms)"], unit="ms")

In [27]:
gyro_df.head()

,epoch (ms),time (01:00),elapsed (s),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:10:08.351,1547219408351,2019-01-11T16:10:08.351,0.00,0.122,-5.488,-3.841,A,bench,heavy,1
2019-01-11 15:10:08.391,1547219408391,2019-01-11T16:10:08.391,0.04,2.195,-9.695,-0.610,A,bench,heavy,1
2019-01-11 15:10:08.431,1547219408431,2019-01-11T16:10:08.431,0.08,2.622,-8.110,-4.024,A,bench,heavy,1
2019-01-11 15:10:08.471,1547219408471,2019-01-11T16:10:08.471,0.12,1.951,-4.695,-4.634,A,bench,heavy,1
2019-01-11 15:10:08.511,1547219408511,2019-01-11T16:10:08.511,0.16,1.524,-2.561,-2.500,A,bench,heavy,1

In [28]:
del acc_df["epoch (ms)"]
del acc_df["time (01:00)"]
del acc_df["elapsed (s)"]

del gyro_df["epoch (ms)"]
del gyro_df["time (01:00)"]
del gyro_df["elapsed (s)"]

Turn Into Function

In [29]:
files = glob("../../data/raw/MetaMotion/MetaMotion/*.csv")

In [30]:
def read_data_from_files(files):
    acc_df = pd.DataFrame()
    gyro_df = pd.DataFrame()
    
    acc_set = 1
    gyro_set = 1
    
    for f in files:
        participant= f.split("-")[0].split("\\")[-1]
        label = f.split("-")[1]
        category = f.split("-")[2].rstrip("_MetaWear_2019")

        df = pd.read_csv(f)

        df["participant"] = participant
        df["label"] = label
        df["category"] = category

        if "Accelerometer" in f:
            df["set"] = acc_set
            acc_set += 1
            acc_df = pd.concat([acc_df, df], ignore_index=True)

        elif "Gyroscope" in f:
            df["set"] = gyro_set
            gyro_set += 1
            gyro_df = pd.concat([gyro_df, df], ignore_index=True)
    
    acc_df.index = pd.to_datetime(acc_df["epoch (ms)"], unit="ms")
    gyro_df.index = pd.to_datetime(gyro_df["epoch (ms)"], unit="ms")
    
    del acc_df["epoch (ms)"]
    del acc_df["time (01:00)"]
    del acc_df["elapsed (s)"]
    
    del gyro_df["epoch (ms)"]
    del gyro_df["time (01:00)"]
    del gyro_df["elapsed (s)"]
    
    return acc_df, gyro_df

In [31]:
acc_df, gyro_df = read_data_from_files(files)

Merging the DataSets

In [32]:
data_merged = pd.concat([acc_df.iloc[:,:3], gyro_df], axis=1)

In [33]:
data_merged

,x-axis (g),y-axis (g),z-axis (g),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.950,NaN,NaN,NaN,-10.671,-1.524,5.976,B,bench,heavy,30.0
2019-01-11 15:08:04.990,NaN,NaN,NaN,-8.720,-2.073,3.171,B,bench,heavy,30.0
2019-01-11 15:08:05.030,NaN,NaN,NaN,0.488,-3.537,-4.146,B,bench,heavy,30.0
2019-01-11 15:08:05.070,NaN,NaN,NaN,0.244,-5.854,3.537,B,bench,heavy,30.0
2019-01-11 15:08:05.110,NaN,NaN,NaN,-0.915,0.061,-2.805,B,bench,heavy,30.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-20 17:35:13.382,-0.060,-1.021,-0.058,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.462,-0.035,-1.037,-0.026,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.542,-0.045,-1.029,-0.033,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.622,-0.039,-1.027,-0.039,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019-01-20 17:35:13.702,-0.049,-1.031,-0.049,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
data_merged.dropna()

,x-axis (g),y-axis (g),z-axis (g),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:10:08.431,0.010,0.964,-0.087,2.622,-8.110,-4.024,A,bench,heavy,1.0
2019-01-11 15:10:08.511,0.000,0.961,-0.069,1.524,-2.561,-2.500,A,bench,heavy,1.0
2019-01-11 15:10:08.591,0.001,0.974,-0.087,1.707,-5.366,0.915,A,bench,heavy,1.0
2019-01-11 15:10:08.671,-0.012,0.971,-0.084,2.683,-4.146,-1.220,A,bench,heavy,1.0
2019-01-11 15:10:08.751,-0.013,0.954,-0.094,1.524,0.610,-3.171,A,bench,heavy,1.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-15 19:04:25.561,0.369,0.591,0.761,11.220,-5.061,-5.061,A,squat,heavy,24.0
2019-01-15 19:04:25.641,0.387,0.566,0.776,3.963,-2.988,-0.793,A,squat,heavy,24.0
2019-01-15 19:04:25.721,0.361,0.574,0.680,15.305,-3.293,-0.671,A,squat,heavy,24.0
2019-01-15 19:04:25.801,0.353,0.583,0.635,30.366,-0.122,-4.573,A,squat,heavy,24.0
2019-01-15 19:04:25.881,0.359,0.605,0.678,14.756,-6.585,-2.378,A,squat,heavy,24.0

In [35]:
data_merged.head()

,x-axis (g),y-axis (g),z-axis (g),x-axis (deg/s),y-axis (deg/s),z-axis (deg/s),participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.950,NaN,NaN,NaN,-10.671,-1.524,5.976,B,bench,heavy,30.0
2019-01-11 15:08:04.990,NaN,NaN,NaN,-8.720,-2.073,3.171,B,bench,heavy,30.0
2019-01-11 15:08:05.030,NaN,NaN,NaN,0.488,-3.537,-4.146,B,bench,heavy,30.0
2019-01-11 15:08:05.070,NaN,NaN,NaN,0.244,-5.854,3.537,B,bench,heavy,30.0
2019-01-11 15:08:05.110,NaN,NaN,NaN,-0.915,0.061,-2.805,B,bench,heavy,30.0

Rename the Columns

In [36]:
data_merged.columns = [
    "acc_x",
    "acc_y",
    "acc_z",
    "gyro_x",
    "gyro_y",
    "gyro_z",
    "participant",
    "label",
    "category",
    "set",
]

Resample the Data (frequency convsersion)

In [37]:
data_merged.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 69677 entries, 2019-01-11 15:08:04.950000 to 2019-01-20 17:35:13.702000
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   acc_x        23578 non-null  float64
 1   acc_y        23578 non-null  float64
 2   acc_z        23578 non-null  float64
 3   gyro_x       47218 non-null  float64
 4   gyro_y       47218 non-null  float64
 5   gyro_z       47218 non-null  float64
 6   participant  47218 non-null  object
 7   label        47218 non-null  object
 8   category     47218 non-null  object
 9   set          47218 non-null  float64
dtypes: float64(7), object(3)
memory usage: 5.8+ MB

In [38]:
data_merged[:100].resample(rule="s").mean(numeric_only=True)

,acc_x,acc_y,acc_z,gyro_x,gyro_y,gyro_z,set
epoch (ms),,,,,,,
2019-01-11 15:08:04,NaN,NaN,NaN,-9.695500,-1.798500,4.573500,30.0
2019-01-11 15:08:05,-0.002222,0.969333,-0.071222,1.007320,-0.731720,-0.399960,30.0
2019-01-11 15:08:06,-0.099231,0.899462,-0.163846,6.978040,2.417120,-11.256200,30.0
2019-01-11 15:08:07,-0.197875,1.120750,-0.124375,1.659833,-2.466222,0.159278,30.0

In [39]:
data_merged[:1000].resample(rule="s").mean(numeric_only=True)

,acc_x,acc_y,acc_z,gyro_x,gyro_y,gyro_z,set
epoch (ms),,,,,,,
2019-01-11 15:08:04,NaN,NaN,NaN,-9.695500,-1.798500,4.573500,30.0
2019-01-11 15:08:05,-0.002222,0.969333,-0.071222,1.007320,-0.731720,-0.399960,30.0
2019-01-11 15:08:06,-0.099231,0.899462,-0.163846,6.978040,2.417120,-11.256200,30.0
2019-01-11 15:08:07,-0.204750,1.055917,-0.156333,1.317040,-2.083000,2.248840,30.0
2019-01-11 15:08:08,-0.079462,0.920462,-0.085692,-9.826840,-4.697560,8.356160,30.0
...,...,...,...,...,...,...,...
2019-01-11 15:10:18,-0.159308,1.022154,-0.169462,-4.687760,-0.229240,-2.634160,1.0
2019-01-11 15:10:19,-0.136167,0.938417,-0.129417,-4.741400,1.731800,14.529320,1.0
2019-01-11 15:10:20,-0.003769,0.938615,-0.106846,6.426880,-5.836560,-4.370720,1.0
2019-01-11 15:10:21,-0.152750,1.017750,-0.182167,1.597440,-6.397600,-5.312120,1.0
2019-01-11 15:10:22,-0.211571,0.890857,-0.174000,4.668929,4.703786,-2.613214,1.0

In [40]:
data_merged[:1000].resample(rule="200ms").mean(numeric_only=True)

,acc_x,acc_y,acc_z,gyro_x,gyro_y,gyro_z,set
epoch (ms),,,,,,,
2019-01-11 15:08:04.800,NaN,NaN,NaN,-9.69550,-1.7985,4.5735,30.0
2019-01-11 15:08:05.000,NaN,NaN,NaN,-2.01220,-0.4270,-1.6218,30.0
2019-01-11 15:08:05.200,0.013500,0.977000,-0.071000,-1.89040,2.4392,0.9388,30.0
2019-01-11 15:08:05.400,-0.001500,0.970500,-0.079500,-1.68260,-0.8904,2.1708,30.0
2019-01-11 15:08:05.600,0.001333,0.971667,-0.064333,2.56080,-0.2560,-1.4146,30.0
...,...,...,...,...,...,...,...
2019-01-11 15:10:21.600,-0.174000,1.092667,-0.153333,-4.96360,-16.4026,21.9026,1.0
2019-01-11 15:10:21.800,-0.219500,1.402500,-0.109000,-7.52440,18.6706,-22.6828,1.0
2019-01-11 15:10:22.000,-0.192000,0.871667,-0.155667,2.60980,8.7070,-14.8658,1.0
2019-01-11 15:10:22.200,-0.227000,0.891000,-0.170000,5.39020,4.0000,-0.3780,1.0
2019-01-11 15:10:22.400,-0.225500,0.919500,-0.205500,6.34125,0.5795,9.9085,1.0

In [41]:
sampling = {
    "acc_x": "mean",
    "acc_y": "mean",
    "acc_z": "mean",
    "gyro_x": "mean",
    "gyro_y": "mean",
    "gyro_z": "mean",
    
    "participant": "last",
    "label": "last",
    "category": "last",
    "set": "last",
}

In [42]:
data_merged[:1000].resample(rule="200ms").apply(sampling)

,acc_x,acc_y,acc_z,gyro_x,gyro_y,gyro_z,participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:04.800,NaN,NaN,NaN,-9.69550,-1.7985,4.5735,B,bench,heavy,30.0
2019-01-11 15:08:05.000,NaN,NaN,NaN,-2.01220,-0.4270,-1.6218,B,bench,heavy,30.0
2019-01-11 15:08:05.200,0.013500,0.977000,-0.071000,-1.89040,2.4392,0.9388,B,bench,heavy,30.0
2019-01-11 15:08:05.400,-0.001500,0.970500,-0.079500,-1.68260,-0.8904,2.1708,B,bench,heavy,30.0
2019-01-11 15:08:05.600,0.001333,0.971667,-0.064333,2.56080,-0.2560,-1.4146,B,bench,heavy,30.0
...,...,...,...,...,...,...,...,...,...,...
2019-01-11 15:10:21.600,-0.174000,1.092667,-0.153333,-4.96360,-16.4026,21.9026,A,bench,heavy,1.0
2019-01-11 15:10:21.800,-0.219500,1.402500,-0.109000,-7.52440,18.6706,-22.6828,A,bench,heavy,1.0
2019-01-11 15:10:22.000,-0.192000,0.871667,-0.155667,2.60980,8.7070,-14.8658,A,bench,heavy,1.0
2019-01-11 15:10:22.200,-0.227000,0.891000,-0.170000,5.39020,4.0000,-0.3780,A,bench,heavy,1.0
2019-01-11 15:10:22.400,-0.225500,0.919500,-0.205500,6.34125,0.5795,9.9085,A,bench,heavy,1.0

In [43]:
data_merged.columns

Index(['acc_x', 'acc_y', 'acc_z', 'gyro_x', 'gyro_y', 'gyro_z', 'participant',
       'label', 'category', 'set'],
      dtype='object')

Split by Day

In [44]:
days = [g for n, g in data_merged.groupby(pd.Grouper(freq="D"))]

In [45]:
data_resampled = pd.concat([df.resample(rule="200ms").apply(sampling).dropna() for df in days],)

In [46]:
data_resampled.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 9009 entries, 2019-01-11 15:08:05.200000 to 2019-01-20 17:33:27.800000
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   acc_x        9009 non-null   float64
 1   acc_y        9009 non-null   float64
 2   acc_z        9009 non-null   float64
 3   gyro_x       9009 non-null   float64
 4   gyro_y       9009 non-null   float64
 5   gyro_z       9009 non-null   float64
 6   participant  9009 non-null   object
 7   label        9009 non-null   object
 8   category     9009 non-null   object
 9   set          9009 non-null   float64
dtypes: float64(7), object(3)
memory usage: 774.2+ KB

In [47]:
data_resampled["label"] = data_resampled["label"].astype(object)
data_resampled["category"] = data_resampled["category"].astype(object)
data_resampled["participant"] = data_resampled["participant"].astype(object)
data_resampled["set"] = data_resampled["set"].astype(int)

In [48]:
data_resampled.head()

,acc_x,acc_y,acc_z,gyro_x,gyro_y,gyro_z,participant,label,category,set
epoch (ms),,,,,,,,,,
2019-01-11 15:08:05.200,0.013500,0.977000,-0.071000,-1.8904,2.4392,0.9388,B,bench,heavy,30
2019-01-11 15:08:05.400,-0.001500,0.970500,-0.079500,-1.6826,-0.8904,2.1708,B,bench,heavy,30
2019-01-11 15:08:05.600,0.001333,0.971667,-0.064333,2.5608,-0.2560,-1.4146,B,bench,heavy,30
2019-01-11 15:08:05.800,-0.024000,0.957000,-0.073500,8.0610,-4.5244,-2.0730,B,bench,heavy,30
2019-01-11 15:08:06.000,-0.028000,0.957667,-0.115000,2.4390,-1.5486,-3.6098,B,bench,heavy,30

Export Dataset

In [49]:
data_resampled.to_pickle("../../data/interim/01_data_processed.pkl")